title: Mohamed Elbanan, MD
description: > # this means to ignore newlines until "baseurl:"
  Mohamed Elbanan,MD Personal Blog. I write about Radiology, Artifical Intelligence and Technology
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elbanan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: iamelbanan #if your site has a twitter account, enter it here

# Author Settings
author: Mohamed Elbanan, MD # add your name
author-img: me.jpg # add your photo
about-author: I am a Radiology Resident and Artificial Intelligence Advocate. Always Eager to keep learning. # add description
social-twitter: iamelbanan
social-github: elbanan # add your Github handle
social-linkedin: mohamedelbanan

# Disqus
discus-identifier: elbanan # add your discus identifier

# Tracker
analytics: UA-116382803-3 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
